# Generated by Django 5.1.4 on 2025-09-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fix_admin_fields'),
    ]

    operations = [
    ]
