# Generated by Django 5.1.4 on 2025-09-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('students', '0004_auto_20250914_1220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='studentbatch',
            name='unique_batch_per_dept_year_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_semester',
        ),
        migrations.AddField(
            model_name='quota',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quota',
            name='display_name',
            field=models.CharField(default='', help_text='Display name for the quota', max_length=100),
        ),
        migrations.AddField(
            model_name='quota',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display purposes'),
        ),
        migrations.AddField(
            model_name='quota',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E'), ('F', 'Section F'), ('G', 'Section G'), ('H', 'Section H'), ('I', 'Section I'), ('J', 'Section J'), ('K', 'Section K'), ('L', 'Section L'), ('M', 'Section M'), ('N', 'Section N'), ('O', 'Section O'), ('P', 'Section P'), ('Q', 'Section Q'), ('R', 'Section R'), ('S', 'Section S'), ('T', 'Section T')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], default='1', help_text='Current semester (legacy)', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='academic_year',
            field=models.CharField(help_text='e.g., 2023-2024', max_length=9),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], default='1', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='studentbatch',
            unique_together={('department', 'academic_year', 'year_of_study', 'section')},
        ),
    ]
