# Generated by Django 5.1.4 on 2025-09-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('students', '0004_auto_20250914_1220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ['display_order', 'name']},
        ),
    ]
