# Generated by Django 5.1.4 on 2025-09-14 07:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_quota_options_and_more'),
    ]

    # BulkAssignment table already exists from earlier migrations/state.
    # No-op to keep migration graph consistent.
    operations = []