# Generated by Django 5.1.4 on 2025-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_cleanup_student_academic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='religion',
            name='display_name',
            field=models.CharField(default='', help_text='Display name for the religion', max_length=100),
        ),
    ]
