# Generated by Django 5.1.4 on 2025-09-14 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_add_display_name_to_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # No-op migration - fields already exist in current model state
    operations = []
