# Generated by Django 5.1.4 on 2025-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_update_display_name_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='display_name',
            field=models.CharField(default='', help_text='Display name for the religion', max_length=100),
        ),
    ]
