# Generated by Django 5.1.4 on 2025-09-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_fix_religion_display_name_default'),
    ]

    operations = [
        migrations.RunSQL(
            # Remove NOT NULL constraint from display_name column
            "ALTER TABLE students_religion ALTER COLUMN display_name DROP NOT NULL;",
            # Reverse operation
            "ALTER TABLE students_religion ALTER COLUMN display_name SET NOT NULL;",
        ),
        migrations.RunSQL(
            # Set default value for display_name column
            "ALTER TABLE students_religion ALTER COLUMN display_name SET DEFAULT '';",
            # Reverse operation
            "ALTER TABLE students_religion ALTER COLUMN display_name DROP DEFAULT;",
        ),
    ]
