# Generated by Django 5.1.4 on 2025-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_fix_religion_display_name_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Display name for the religion', max_length=100, null=True),
        ),
    ]
