# Generated by Django 5.1.4 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_make_display_name_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='religion',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display purposes'),
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['display_order', 'name']},
        ),
    ]
