# Generated by Django 5.1.4 on 2025-01-27 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_add_display_order_to_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='display_name',
            field=models.CharField(default='', help_text='Display name for the caste', max_length=100),
        ),
        migrations.AddField(
            model_name='caste',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display purposes'),
        ),
        migrations.AddField(
            model_name='caste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caste',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_castes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='caste',
            options={'ordering': ['display_order', 'name']},
        ),
    ]
