# Generated by Django 5.1.4 on 2025-09-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('students', '0019_add_missing_fields_to_caste'),
    ]

    operations = [
    ]
