# Generated by Django 5.1.4 on 2025-09-16 15:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Select (Dropdown)'), ('multiselect', 'Multi-Select'), ('boolean', 'Yes/No'), ('textarea', 'Long Text'), ('file', 'File Upload'), ('url', 'URL')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, help_text='For select/multiselect fields, provide options as JSON array', null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=200, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_custom_is_acti_aa404e_idx'), models.Index(fields=['field_type'], name='core_custom_field_t_d7344c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('contact_type', models.CharField(choices=[('SELF', 'Self'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('EMERGENCY', 'Emergency'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_contac_content_92c564_idx'), models.Index(fields=['contact_type'], name='core_contac_contact_340f61_idx')],
                'unique_together': {('content_type', 'object_id', 'contact_type', 'is_primary')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('value', models.TextField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='custom_field_files/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfield')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_custom_content_d2b966_idx'), models.Index(fields=['custom_field'], name='core_custom_custom__5ae1d7_idx')],
                'unique_together': {('content_type', 'object_id', 'custom_field')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('document_type', models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('TRANSCRIPT', 'Academic Transcript'), ('MEDICAL', 'Medical Record'), ('IMMUNIZATION', 'Immunization Record'), ('PHOTO_ID', 'Photo ID'), ('RESUME', 'Resume/CV'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('PHOTO', 'Photograph'), ('PAN_CARD', 'PAN Card'), ('AADHAR_CARD', 'Aadhar Card'), ('OTHER', 'Other')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_docume_content_343c2e_idx'), models.Index(fields=['document_type'], name='core_docume_documen_5649ee_idx'), models.Index(fields=['is_verified'], name='core_docume_is_veri_cf81c9_idx')],
            },
        ),
    ]
