# Generated by Django 5.1.4 on 2025-09-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('departments', '0002_initial'),
        ('placements', '0002_enhanced_placements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyfeedback',
            name='unique_company_feedback',
        ),
        migrations.RemoveConstraint(
            model_name='placementstatistics',
            name='unique_placement_stats',
        ),
        migrations.AlterUniqueTogether(
            name='companyfeedback',
            unique_together={('company', 'drive')},
        ),
        migrations.AlterUniqueTogether(
            name='placementstatistics',
            unique_together={('academic_year', 'department', 'program')},
        ),
    ]
