# Generated by Django 5.1.4 on 2025-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicollection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apitestsuite',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='apienvironment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apitestresult',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='apitestsuite',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='apitestresult',
            name='request',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='apitestsuite',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='apitestresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='apitestsuiteresult',
            name='results',
        ),
        migrations.RemoveField(
            model_name='apitestsuiteresult',
            name='suite',
        ),
        migrations.DeleteModel(
            name='APIAutomation',
        ),
        migrations.DeleteModel(
            name='APICollection',
        ),
        migrations.DeleteModel(
            name='APIEnvironment',
        ),
        migrations.DeleteModel(
            name='APIRequest',
        ),
        migrations.DeleteModel(
            name='APITest',
        ),
        migrations.DeleteModel(
            name='APITestResult',
        ),
        migrations.DeleteModel(
            name='APITestSuite',
        ),
        migrations.DeleteModel(
            name='APITestSuiteResult',
        ),
    ]
