# Cache (Redis if REDIS_URL provided; else local memory cache)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local-default',
        'TIMEOUT': 300,
    }
}

import os
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')
if REDIS_URL:
    CACHES['default'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'TIMEOUT': 300,  # 5 minutes default
        'KEY_PREFIX': 'campushub',
        'VERSION': 1,
    }
"""
Django settings for campshub360 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers, default_methods
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env if present
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In development, generate a temporary key if not provided
from django.core.management.utils import get_random_secret_key
import secrets
import string

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # Generate a strong 50+ character secret key
    SECRET_KEY = os.getenv('DJANGO_DEV_SECRET') or ''.join(
        secrets.choice(string.ascii_letters + string.digits + '!@#$%^&*()_+-=[]{}|;:,.<>?') 
        for _ in range(50)
    )

# Validate SECRET_KEY strength
if len(SECRET_KEY) < 50 or SECRET_KEY == 'change-this-to-a-strong-secret':
    import warnings
    warnings.warn(
        "SECRET_KEY is too weak or using default value. Please set a strong, random SECRET_KEY in production.",
        UserWarning
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Hosts the app will accept. Defaults include EC2 IP/DNS and our domains.
_env_allowed_hosts = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []
_default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    'testserver',
    # Project domains
    '.campushub360.xyz',
    'campushub360.xyz',
    'www.campushub360.xyz',
    'api.campushub360.xyz',
    # EC2 public IP and DNS (adjustable via env if needed)
    '13.232.220.214',
    'ec2-13-232-220-214.ap-south-1.compute.amazonaws.com',
    # Wildcard for any host under the AWS regional domain (covers rotating EC2 DNS)
    '.ap-south-1.compute.amazonaws.com',
]

# Normalize and de-duplicate while dropping empties
ALLOWED_HOSTS = [h.strip() for h in (_env_allowed_hosts or _default_allowed_hosts) if h and h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    # Core app must be first to provide base models
    'core',
    'accounts',
    'dashboard',
    'departments',
    'academics',
    'students',
    'faculty',
    'enrollment',
    'attendance',
    'placements',
    'grads',
    'rnd',
    'facilities',
    'exams',
    'fees',
    'transportation',
    'mentoring',
    'feedback',
    'assignments',
    # 'docs' app removed
    'campshub360',
    'achievements',
    'events',
]

# drf-spectacular removed

# Optionally include ratelimit if installed, to avoid hard dependency during local dev
try:
    import ratelimit  # type: ignore
    INSTALLED_APPS.append('ratelimit')
except Exception:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'campshub360.csrf.CSRFEnsureTokenMiddleware',  # Ensure CSRF tokens for admin
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'campshub360.metrics.MetricsMiddleware',
    'campshub360.audit.AuditLogMiddleware',
    # Enable RLS middleware only when ENABLE_RLS=true
    *(['campshub360.db_tenant.SetCurrentDepartmentMiddleware'] if os.getenv('ENABLE_RLS', 'False').lower() == 'true' else []),
]

ROOT_URLCONF = 'campshub360.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campshub360.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.getenv('DATABASE_URL')
if _database_url:
    # Prefer DATABASE_URL if provided (supports sqlite/postgres/etc.)
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'campushub360'),
            'USER': os.getenv('POSTGRES_USER', 'campushub'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'Campushub123'),
            'HOST': os.getenv('POSTGRES_HOST', 'campushub.cl00sagomrhg.ap-south-1.rds.amazonaws.com'),
            'PORT': int(os.getenv('POSTGRES_PORT', '5432')),
            'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '600')),  # 10 minutes
            'OPTIONS': {
                'connect_timeout': int(os.getenv('POSTGRES_CONNECT_TIMEOUT', '10')),
                'sslmode': os.getenv('POSTGRES_SSL_MODE', 'require'),
            },
        },
        'read_replica': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'campushub360'),
            'USER': os.getenv('POSTGRES_USER', 'campushub'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'Campushub123'),
            'HOST': os.getenv('POSTGRES_REPLICA_HOST', os.getenv('POSTGRES_HOST', 'campushub.cl00sagomrhg.ap-south-1.rds.amazonaws.com')),
            'PORT': int(os.getenv('POSTGRES_REPLICA_PORT', os.getenv('POSTGRES_PORT', '5432'))),
            'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                'connect_timeout': int(os.getenv('POSTGRES_CONNECT_TIMEOUT', '10')),
                'sslmode': os.getenv('POSTGRES_SSL_MODE', 'require'),
            },
        }
    }

# Database configuration


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Storage Configuration
# For Django 4.2+ compatibility with health_check.storage
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Modern Django 4.2+ storage configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'campshub360.pagination.DefaultCursorPagination',
    'PAGE_SIZE': int(os.getenv('API_PAGE_SIZE', '50')),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'campshub360.exceptions.custom_exception_handler',
}

# Schema generation removed

# SimpleJWT settings (optional sane defaults)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '1440'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH', 'False').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': True,
}

# Use custom user model
AUTH_USER_MODEL = 'accounts.User'

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Auth redirects
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
LOGOUT_REDIRECT_URL = 'admin:login'

# Caching - Redis if available, fallback to local memory cache
if os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300')),
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS', '2000')),
                    'retry_on_timeout': True,
                },
            }
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'TIMEOUT': int(os.getenv('SESSION_CACHE_TIMEOUT', '86400')),  # 24 hours
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS', '2000')),
                    'retry_on_timeout': True,
                },
            }
        },
        'query_cache': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'TIMEOUT': int(os.getenv('QUERY_CACHE_TIMEOUT', '600')),  # 10 minutes
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS', '2000')),
                    'retry_on_timeout': True,
                },
            }
        }
    }
else:
    # Fallback to local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300')),
            'OPTIONS': {
                'MAX_ENTRIES': 10000,  # Increased for better performance
            }
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake-sessions',
            'TIMEOUT': int(os.getenv('SESSION_CACHE_TIMEOUT', '86400')),  # 24 hours
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        },
        'query_cache': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake-query',
            'TIMEOUT': int(os.getenv('QUERY_CACHE_TIMEOUT', '600')),  # 10 minutes
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Cache session engine for high performance
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = 'sessions'

# Security Settings for High-Performance Production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

# CSRF Protection
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
# Allow frontend (React/Vite/Postman) to read CSRF cookie and send via header
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_USE_SESSIONS = os.getenv('CSRF_USE_SESSIONS', 'False').lower() == 'true'
# Ensure CSRF cookie is always set and accessible
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_AGE = 31449600  # 1 year
CSRF_COOKIE_DOMAIN = None  # Allow for localhost development

# Session Security
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
# For cross-site cookies when frontend runs on a different origin
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_AGE = 86400  # 1 day

# Performance Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Database Query Optimization (PostgreSQL specific)
if DATABASES['default']['ENGINE'].endswith('postgresql'):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'sslmode': os.getenv('POSTGRES_SSL_MODE', 'require'),
    })
    # Connection Pooling
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes
    if 'read_replica' in DATABASES:
        DATABASES['read_replica']['CONN_MAX_AGE'] = 600

# Optional: route reads to replica
DATABASE_ROUTERS = ['campshub360.db_routers.ReadReplicaRouter']

# CORS settings
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://0.0.0.0:3000,https://localhost:3000,https://127.0.0.1:3000,'
    'http://localhost:5173,http://127.0.0.1:5173,http://0.0.0.0:5173,https://localhost:5173,https://127.0.0.1:5173,'
    'https://campushub360.xyz,https://www.campushub360.xyz,https://api.campushub360.xyz,'
    'http://13.232.220.214,https://13.232.220.214,http://13.232.220.214:8000,https://13.232.220.214:8000,'
    'http://ec2-13.232.220.214.ap-south-1.compute.amazonaws.com,https://ec2-13.232-220-214.ap-south-1.compute.amazonaws.com,'
    'http://ec2-13.232.220.214.ap-south-1.compute.amazonaws.com:8000,https://ec2-13.232.220.214.ap-south-1.compute.amazonaws.com:8000,'
    'http://13.201.129.254,https://13.201.129.254,http://ec2-13-201-129-254.ap-south-1.compute.amazonaws.com,https://ec2-13-201-129-254.ap-south-1.compute.amazonaws.com'
).split(',')
CORS_ALLOW_CREDENTIALS = True

# CSRF settings
_env_csrf = os.getenv('CSRF_TRUSTED_ORIGINS')
if _env_csrf:
    CSRF_TRUSTED_ORIGINS = [h.strip() for h in _env_csrf.split(',') if h and h.strip()]
else:
    # Auto-build CSRF trusted origins from allowed hosts for common ports used by Django/Vite
    _schemes = ['http://', 'https://']
    _ports = ['', ':8000', ':5173', ':3000', ':8080', ':9000']
    _csrf = []
    
    # Handle wildcard ALLOWED_HOSTS in development
    if '*' in ALLOWED_HOSTS or DEBUG:
        # In development, include all common localhost variations
        _csrf.extend([
            'http://localhost', 'https://localhost',
            'http://127.0.0.1', 'https://127.0.0.1',
            'http://0.0.0.0', 'https://0.0.0.0',
        ])
        # Add common development ports
        for port in _ports:
            if port:  # Skip empty port
                _csrf.extend([
                    f'http://localhost{port}',
                    f'https://localhost{port}',
                    f'http://127.0.0.1{port}',
                    f'https://127.0.0.1{port}',
                ])
    else:
        # Production: build from specific allowed hosts
        for host in ALLOWED_HOSTS:
            h = host.lstrip('.')
            for s in _schemes:
                for p in _ports:
                    _csrf.append(f"{s}{h}{p}")
    
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_csrf))

# Development override: allow all hosts and permissive CORS for local testing
if DEBUG:
    ALLOWED_HOSTS = ['*']
    # Allow any origin via regex while still permitting credentials in development
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^https?://.*$']
    # Relax SameSite in development for local cross-origin testing
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'

# Explicit CORS headers/methods
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
    'x-csrftoken',
]
CORS_ALLOW_METHODS = list(default_methods) + [
    'PATCH',
]

# Broad but scoped CORS origin regexes for IPs, localhost, AWS EC2 DNS and project domain
# This allows Vite dev servers (:5173) and Postman/browser origins across http/https
CORS_ALLOWED_ORIGIN_REGEXES = list(set((globals().get('CORS_ALLOWED_ORIGIN_REGEXES') or []) + [
    r'^https?://(localhost|127\.0\.0\.1|0\.0\.0\.0)(:\\d+)?$',
    r'^https?://(\\d{1,3}\.){3}\\d{1,3}(:\\d+)?$',
    r'^https?://([a-zA-Z0-9-]+\.)*campushub360\\.xyz(:\\d+)?$',
    r'^https?://([a-zA-Z0-9-]+\.)*compute\\.amazonaws\\.com(:\\d+)?$',
]))

# Custom CSRF failure handler to avoid generic 500s and add logging
CSRF_FAILURE_VIEW = 'campshub360.csrf.csrf_failure'

# Auth rate limits via env (used by views with decorators)
AUTH_RATE_LIMIT_TOKEN = os.getenv('AUTH_RATE_LIMIT_TOKEN', '5/m')
AUTH_RATE_LIMIT_REFRESH = os.getenv('AUTH_RATE_LIMIT_REFRESH', '10/m')

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@campushub360.com')

# Gunicorn Configuration
GUNICORN_BIND = os.getenv('GUNICORN_BIND', '127.0.0.1:8000')
GUNICORN_WORKERS = int(os.getenv('GUNICORN_WORKERS', '4'))
GUNICORN_WORKER_CLASS = os.getenv('GUNICORN_WORKER_CLASS', 'sync')
GUNICORN_WORKER_CONNECTIONS = int(os.getenv('GUNICORN_WORKER_CONNECTIONS', '1000'))
GUNICORN_TIMEOUT = int(os.getenv('GUNICORN_TIMEOUT', '30'))
GUNICORN_KEEPALIVE = int(os.getenv('GUNICORN_KEEPALIVE', '5'))
GUNICORN_MAX_REQUESTS = int(os.getenv('GUNICORN_MAX_REQUESTS', '1000'))
GUNICORN_MAX_REQUESTS_JITTER = int(os.getenv('GUNICORN_MAX_REQUESTS_JITTER', '100'))

# Update Security Settings to use environment variables
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))  # 0 for development, 31536000 for production
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() == 'true'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').lower() == 'true'

# Production security settings (only enabled when not in debug mode)
if not DEBUG:
    # Enable HSTS only in production
    if SECURE_HSTS_SECONDS == 0:
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    
    # Enable secure cookies in production unless explicitly disabled via env
    # Useful for testing over plain HTTP on IP/port where secure cookies won't be sent
    if os.getenv('FORCE_SECURE_COOKIES', 'False').lower() == 'true':
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True

    # When frontend is on a different domain and cookies are needed across sites, prefer "None"
    # Configure via env to avoid forcing a cross-site policy unintentionally
    if os.getenv('CROSS_SITE_COOKIES', 'False').lower() == 'true':
        CSRF_COOKIE_SAMESITE = 'None'
        SESSION_COOKIE_SAMESITE = 'None'

    # Honor proxy headers from ALB/Nginx to correctly detect HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    # Enable compressed manifest static files for long-lived caching
    STORAGES["staticfiles"]["BACKEND"] = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    # Ensure host validation covers EC2 public DNS / custom domains via env
    # Example env: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com,ec2-xx-xx-xx-xx.compute-1.amazonaws.com

    # Basic logging to capture 500s and CSRF issues in production
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '[{levelname}] {asctime} {name} {module}:{lineno} {message}',
                'style': '{',
            },
            'simple': {
                'format': '[{levelname}] {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
            'security_console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'db_console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper(),
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
            'django.security.DisallowedHost': {
                'handlers': ['security_console'],
                'level': 'ERROR',
                'propagate': False,
            },
            'campshub360': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            # Enable DB query logging (high-volume). Use env DB_LOG_LEVEL to control.
            'django.db.backends': {
                'handlers': ['db_console'],
                'level': os.getenv('DB_LOG_LEVEL', 'WARNING').upper(),
                'propagate': False,
            },
        },
    }
