# Generated by Django 5.1.4 on 2025-09-11 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_students',
            field=models.ManyToManyField(blank=True, help_text='Specific students this assignment is assigned to', related_name='assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.assignmentcategory'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='assignments.assignmentcomment'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='members',
            field=models.ManyToManyField(related_name='assignment_groups', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='assignments.assignmentgrade'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.assignmentcategory'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['faculty', 'status'], name='assignments_faculty_44f346_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_7a9bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_date'], name='assignments_status_a60348_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['academic_year', 'semester'], name='assignments_academi_f5d3af_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['assignment', 'created_at'], name='assignments_assignm_8b0a16_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['author'], name='assignments_author__575e37_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentgrade',
            index=models.Index(fields=['graded_at'], name='assignments_graded__da07b9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentgrade',
            index=models.Index(fields=['grade_letter'], name='assignments_grade_l_2abd08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentgroup',
            unique_together={('assignment', 'group_name')},
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student'], name='assignments_assignm_e2e7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['submission_date'], name='assignments_submiss_f09516_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignments_status_4386ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status', 'submission_date'], name='assignments_assignm_dd5c1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignmentfile',
            index=models.Index(fields=['assignment', 'file_type'], name='assignments_assignm_99f76c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentfile',
            index=models.Index(fields=['uploaded_at'], name='assignments_uploade_8afc6d_idx'),
        ),
    ]
