# Generated by Django 5.1.4 on 2025-09-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this assignment is assigned to', related_name='course_assignments', to='academics.course'),
        ),
    ]
