# Generated by Django 5.1.4 on 2025-09-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_assigned_to_courses'),
        ('students', '0019_add_missing_fields_to_caste'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_academi_05bfd9_idx',
            old_name='assignments_academi_f5d3af_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='students.semester'),
        ),
    ]
