# Generated by Django 5.1.4 on 2025-09-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_assignments_academi_f5d3af_idx_assignments_academi_05bfd9_idx_and_more'),
    ]

    operations = [
    ]
