# Generated by Django 5.1.4 on 2025-09-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('assignments', '0006_add_enhanced_assignment_fields'),
        ('departments', '0002_initial'),
        ('faculty', '0001_initial'),
        ('students', '0019_add_missing_fields_to_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When the assignment becomes visible and open for submissions', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Optional hard close; after this, no submissions are allowed', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Primary course for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assignments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_section',
            field=models.ForeignKey(blank=True, help_text='Primary course section for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assignments', to='academics.coursesection'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assignments', to='departments.department'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when status first became PUBLISHED', null=True),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['department'], name='assignments_departm_e341a8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assignments_course__91e566_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course_section'], name='assignments_course__6a3b17_idx'),
        ),
    ]
