# Generated by Django 5.1.4 on 2025-09-15 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('departments', '0002_initial'),
        ('grads', '0001_initial'),
        ('students', '0019_add_missing_fields_to_caste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termgpa',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpas', to='students.semester'),
        ),
        migrations.AlterModelOptions(
            name='termgpa',
            options={'ordering': ['-semester__academic_year__year']},
        ),
        migrations.AlterUniqueTogether(
            name='termgpa',
            unique_together={('student', 'semester')},
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['student'], name='grads_cours_student_d3308a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['term'], name='grads_cours_term_id_4decf6_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['course_section'], name='grads_cours_course__ad6f38_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['passed'], name='grads_cours_passed_dc13f3_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['letter'], name='grads_grade_letter_1c08a6_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['is_active'], name='grads_grade_is_acti_bfccfd_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['department'], name='grads_grade_departm_9d38e8_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['program'], name='grads_grade_program_db3245_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseresult',
            constraint=models.CheckConstraint(condition=models.Q(('internal_marks__gte', 0), ('external_marks__gte', 0)), name='course_result_nonnegative_marks'),
        ),
        migrations.AddConstraint(
            model_name='courseresult',
            constraint=models.CheckConstraint(condition=models.Q(('internal_marks__lte', 100), ('external_marks__lte', 100)), name='course_result_marks_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__gte', 0), ('max_score__lte', 100), ('min_score__lte', models.F('max_score'))), name='grade_scale_score_bounds_valid'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('grade_points__gte', 0)), name='grade_scale_points_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='term_date_range_valid'),
        ),
        migrations.RemoveField(
            model_name='termgpa',
            name='term',
        ),
    ]
