# Generated by Django 5.1.4 on 2025-09-15 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('grads', '0002_alter_termgpa_options_alter_termgpa_unique_together_and_more'),
        ('students', '0019_add_missing_fields_to_caste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidTermGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('midterm_grade', models.CharField(blank=True, max_length=2)),
                ('midterm_grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['student__roll_number', 'course_section'],
            },
        ),
        migrations.CreateModel(
            name='SemesterGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_credits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-semester__academic_year__year'],
            },
        ),
        migrations.CreateModel(
            name='SemesterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_grade', models.CharField(blank=True, max_length=2)),
                ('final_grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['student__roll_number', 'course_section'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='course_section',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='term',
        ),
        migrations.RemoveField(
            model_name='graduaterecord',
            name='program',
        ),
        migrations.RemoveField(
            model_name='graduaterecord',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='termgpa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='termgpa',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='termgpa',
            name='student',
        ),
        migrations.RemoveIndex(
            model_name='gradescale',
            name='grads_grade_letter_1c08a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradescale',
            name='grads_grade_is_acti_bfccfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradescale',
            name='grads_grade_departm_9d38e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradescale',
            name='grads_grade_program_db3245_idx',
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='letter',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_grades', to='academics.coursesection'),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_grades', to='students.semester'),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='semestergpa',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpas', to='students.semester'),
        ),
        migrations.AddField(
            model_name='semestergpa',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_gpas', to='students.student'),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grades', to='academics.coursesection'),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grades', to='students.semester'),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grades', to='students.student'),
        ),
        migrations.DeleteModel(
            name='CourseResult',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='GraduateRecord',
        ),
        migrations.DeleteModel(
            name='TermGPA',
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='department',
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='program',
        ),
        migrations.AddIndex(
            model_name='midtermgrade',
            index=models.Index(fields=['student'], name='grads_midte_student_25053e_idx'),
        ),
        migrations.AddIndex(
            model_name='midtermgrade',
            index=models.Index(fields=['course_section'], name='grads_midte_course__6b166b_idx'),
        ),
        migrations.AddIndex(
            model_name='midtermgrade',
            index=models.Index(fields=['semester'], name='grads_midte_semeste_1aacfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='midtermgrade',
            constraint=models.CheckConstraint(condition=models.Q(('midterm_marks__gte', 0), ('midterm_marks__lte', 100)), name='midterm_marks_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='midtermgrade',
            unique_together={('student', 'course_section', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semestergpa',
            unique_together={('student', 'semester')},
        ),
        migrations.AddIndex(
            model_name='semestergrade',
            index=models.Index(fields=['student'], name='grads_semes_student_627656_idx'),
        ),
        migrations.AddIndex(
            model_name='semestergrade',
            index=models.Index(fields=['course_section'], name='grads_semes_course__fbbbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='semestergrade',
            index=models.Index(fields=['semester'], name='grads_semes_semeste_1251f4_idx'),
        ),
        migrations.AddIndex(
            model_name='semestergrade',
            index=models.Index(fields=['passed'], name='grads_semes_passed_4d3af1_idx'),
        ),
        migrations.AddConstraint(
            model_name='semestergrade',
            constraint=models.CheckConstraint(condition=models.Q(('final_marks__gte', 0), ('final_marks__lte', 100)), name='final_marks_valid_range'),
        ),
        migrations.AlterUniqueTogether(
            name='semestergrade',
            unique_together={('student', 'course_section', 'semester')},
        ),
    ]
