# Generated by Django 5.1.4 on 2025-09-15 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_coursesection_options_and_more'),
        ('grads', '0003_simplify_grades_system'),
        ('students', '0019_add_missing_fields_to_caste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='midtermgrade',
            name='midterm_marks_valid_range',
        ),
        migrations.RemoveConstraint(
            model_name='semestergrade',
            name='final_marks_valid_range',
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total marks for the exam (e.g., 50, 100)', max_digits=6),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total marks for the exam (e.g., 50, 100)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='midtermgrade',
            name='midterm_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks obtained by student', max_digits=6),
        ),
        migrations.AlterField(
            model_name='semestergrade',
            name='final_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks obtained by student', max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='midtermgrade',
            constraint=models.CheckConstraint(condition=models.Q(('midterm_marks__gte', 0)), name='midterm_marks_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='midtermgrade',
            constraint=models.CheckConstraint(condition=models.Q(('total_marks__gt', 0)), name='total_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='midtermgrade',
            constraint=models.CheckConstraint(condition=models.Q(('midterm_marks__lte', models.F('total_marks'))), name='midterm_marks_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='semestergrade',
            constraint=models.CheckConstraint(condition=models.Q(('final_marks__gte', 0)), name='final_marks_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='semestergrade',
            constraint=models.CheckConstraint(condition=models.Q(('total_marks__gt', 0)), name='final_total_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='semestergrade',
            constraint=models.CheckConstraint(condition=models.Q(('final_marks__lte', models.F('total_marks'))), name='final_marks_lte_total'),
        ),
    ]
