# Generated by Django 5.1.4 on 2025-09-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0004_add_total_marks_and_percentage'),
        ('students', '0019_add_missing_fields_to_caste'),
    ]

    operations = [
        # Add description field to GradeScale
        migrations.AddField(
            model_name='gradescale',
            name='description',
            field=models.CharField(default='', help_text='Grade description (e.g., Outstanding, Excellent)', max_length=50),
            preserve_default=False,
        ),
        
        # Rename gpa to sgpa in SemesterGPA
        migrations.RenameField(
            model_name='semestergpa',
            old_name='gpa',
            new_name='sgpa',
        ),
        
        # Add new fields to SemesterGPA
        migrations.AddField(
            model_name='semestergpa',
            name='total_quality_points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quality points earned', max_digits=8),
        ),
        migrations.AddField(
            model_name='semestergpa',
            name='academic_standing',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent (SGPA ≥ 8.0)'), ('VERY_GOOD', 'Very Good (SGPA ≥ 7.0)'), ('GOOD', 'Good (SGPA ≥ 6.0)'), ('SATISFACTORY', 'Satisfactory (SGPA ≥ 5.0)'), ('PASS', 'Pass (SGPA ≥ 4.0)'), ('PROBATION', 'Academic Probation (SGPA < 4.0)')], max_length=20),
        ),
        migrations.AddField(
            model_name='semestergpa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='semestergpa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Create CumulativeGPA model
        migrations.CreateModel(
            name='CumulativeGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative Grade Point Average', max_digits=4, null=True)),
                ('total_credits_earned', models.PositiveIntegerField(default=0, help_text='Total credits earned across all semesters')),
                ('total_quality_points', models.DecimalField(decimal_places=2, default=0, help_text='Total quality points earned', max_digits=10)),
                ('classification', models.CharField(blank=True, choices=[('FIRST_CLASS_DISTINCTION', 'First Class with Distinction (CGPA ≥ 8.0)'), ('FIRST_CLASS', 'First Class (CGPA ≥ 7.0)'), ('SECOND_CLASS', 'Second Class (CGPA ≥ 6.0)'), ('PASS_CLASS', 'Pass Class (CGPA ≥ 4.0)'), ('FAIL', 'Fail (CGPA < 4.0)')], max_length=30)),
                ('is_eligible_for_graduation', models.BooleanField(default=False)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_gpa', to='students.student')),
            ],
            options={
                'verbose_name': 'Cumulative GPA (CGPA)',
                'verbose_name_plural': 'Cumulative GPAs (CGPA)',
            },
        ),
        
        # Update SemesterGPA verbose names
        migrations.AlterModelOptions(
            name='semestergpa',
            options={'ordering': ['-semester__academic_year__year'], 'verbose_name': 'Semester GPA (SGPA)', 'verbose_name_plural': 'Semester GPAs (SGPA)'},
        ),
    ]
