# Generated by Django 5.1.4 on 2025-09-16 00:53

from django.db import migrations, models
from django.utils import timezone


def set_created_at_defaults(apps, schema_editor):
    """Set default created_at values for existing records"""
    SemesterGPA = apps.get_model('grads', 'SemesterGPA')
    for gpa in SemesterGPA.objects.filter(created_at__isnull=True):
        gpa.created_at = timezone.now()
        gpa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0005_indian_grading_system_enhancement'),
    ]

    operations = [
        migrations.RunPython(set_created_at_defaults),
        migrations.AlterField(
            model_name='semestergpa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
