# Generated by Django 5.1.4 on 2025-09-16 00:58

from django.db import migrations, models
from django.utils import timezone


def set_updated_at_defaults(apps, schema_editor):
    """Set default updated_at values for existing records"""
    SemesterGPA = apps.get_model('grads', 'SemesterGPA')
    for gpa in SemesterGPA.objects.filter(updated_at__isnull=True):
        gpa.updated_at = timezone.now()
        gpa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0006_fix_created_at_field'),
    ]

    operations = [
        migrations.RunPython(set_updated_at_defaults),
        migrations.AlterField(
            model_name='semestergpa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
