# Generated by Django 5.1.4 on 2025-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0007_fix_updated_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, help_text='Grade points for the letter (0-10)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='semestergpa',
            name='sgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester Grade Point Average', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='semestergpa',
            name='total_credits',
            field=models.PositiveIntegerField(default=0, help_text='Total credits earned in this semester'),
        ),
    ]
