# Generated by Django 5.1.4 on 2025-09-10 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deputy_head',
            field=models.ForeignKey(blank=True, help_text='Deputy head of department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_headed_departments_new', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Current head of department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments_new', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Parent department if this is a sub-department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='departments.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='departments.department'),
        ),
        migrations.AddField(
            model_name='departmentdocument',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='departments.department'),
        ),
        migrations.AddField(
            model_name='departmentdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='departments.department'),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Event organizer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='departmentresource',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='departments.department'),
        ),
        migrations.AddField(
            model_name='departmentresource',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_35a421_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['short_name'], name='departments_short_n_f97840_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_type'], name='departments_departm_d1db1a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['status'], name='departments_status_b12c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='departments_is_acti_51d68f_idx'),
        ),
    ]
