# Generated by Django 5.1.4 on 2025-09-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0019_add_missing_fields_to_caste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic year for enrollment', max_length=9)),
                ('semester', models.CharField(help_text='Semester for enrollment', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('auto_enroll_new_students', models.BooleanField(default=True, help_text='Automatically enroll new students added to this batch')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course to enroll the batch in', on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='academics.course')),
                ('course_section', models.ForeignKey(blank=True, help_text='Specific course section (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='academics.coursesection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student_batch', models.ForeignKey(help_text='Student batch to enroll', on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='students.studentbatch')),
            ],
            options={
                'verbose_name': 'Batch Course Enrollment',
                'verbose_name_plural': 'Batch Course Enrollments',
                'ordering': ['-enrollment_date', 'student_batch__batch_name', 'course__code'],
                'indexes': [models.Index(fields=['student_batch', 'status'], name='academics_b_student_e41e92_idx'), models.Index(fields=['course', 'status'], name='academics_b_course__cd5ff3_idx'), models.Index(fields=['academic_year', 'semester', 'status'], name='academics_b_academi_4336bf_idx')],
                'unique_together': {('student_batch', 'course', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this prerequisite is mandatory')),
                ('minimum_grade', models.CharField(blank=True, help_text='Minimum grade required (e.g., C, B+)', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course that has prerequisites', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_rules', to='academics.course')),
                ('prerequisite_course', models.ForeignKey(help_text='Prerequisite course', on_delete=django.db.models.deletion.CASCADE, related_name='required_for_courses', to='academics.course')),
                ('student_batch', models.ForeignKey(blank=True, help_text='Specific batch (null means applies to all batches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisites', to='students.studentbatch')),
            ],
            options={
                'verbose_name': 'Course Prerequisite',
                'verbose_name_plural': 'Course Prerequisites',
                'unique_together': {('course', 'prerequisite_course', 'student_batch')},
            },
        ),
    ]
