# Generated by Django 5.1.4 on 2025-09-14 14:44

from django.db import migrations


def fix_section_number_data(apps, schema_editor):
    """
    Fix existing CourseSection data by truncating section_number to 1 character if needed
    """
    CourseSection = apps.get_model('academics', 'CourseSection')
    
    # Get all existing course sections
    sections = CourseSection.objects.all()
    
    for section in sections:
        # Fix section_number if it's longer than 1 character
        if len(section.section_number) > 1:
            # Take only the first character
            section.section_number = section.section_number[0]
            section.save()


def reverse_fix_section_number_data(apps, schema_editor):
    """
    Reverse the data fix (if needed)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_batchcourseenrollment_courseprerequisite'),
    ]

    operations = [
        migrations.RunPython(fix_section_number_data, reverse_fix_section_number_data),
    ]
