# Generated by Django 5.1.4 on 2025-09-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_fix_section_number_data'),
        ('faculty', '0001_initial'),
        ('students', '0019_add_missing_fields_to_caste'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursesection',
            name='course_section_enrollment_not_exceed_capacity',
        ),
        migrations.RemoveIndex(
            model_name='coursesection',
            name='academics_c_faculty_f36357_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursesection',
            name='idx_section_course_year_sem',
        ),
        migrations.RemoveIndex(
            model_name='coursesection',
            name='idx_section_year_sem_active',
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='semester',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='student_batch',
            field=models.ForeignKey(blank=True, help_text='Student batch assigned to this section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='students.studentbatch'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='current_enrollment',
            field=models.PositiveIntegerField(default=0, help_text='Current number of enrolled students (optional)'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum students for this section (optional)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('course', 'student_batch')},
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['faculty'], name='academics_c_faculty_2fe907_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'student_batch'], name='idx_section_course_batch'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['student_batch'], name='idx_section_student_batch'),
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['course__code', 'student_batch__batch_name'], 'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
    ]
