# Generated by Django 5.1.4 on 2025-09-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('academics', '0005_alter_coursesection_options_and_more'),
    ]

    operations = [
    ]
