# Generated by Django 5.1.4 on 2025-09-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_merge_20250919_1505'),
    ]

    operations = [
    ]
