# Generated by Django 5.1.4 on 2025-09-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academictimetableslot'),
        ('academics', '0007_auto_20250920_1245'),
    ]

    operations = [
    ]
