# Generated by Django 5.1.4 on 2025-09-19 19:27

from django.db import migrations, models
from django.db.models import deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_add_missing_timestamp_fields'),
        ('students', '0020_merge_0002_initial_0019_add_missing_fields_to_caste'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active academic period')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this academic period is active')),
                ('period_start', models.DateField(help_text='Start date of this academic period')),
                ('period_end', models.DateField(help_text='End date of this academic period')),
                ('description', models.TextField(blank=True, help_text='Additional description for this academic period')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='academic_periods', to='students.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='created_academic_periods', to='accounts.user')),
                ('semester', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='academic_periods', to='students.semester')),
            ],
            options={
                'verbose_name': 'Academic Period',
                'verbose_name_plural': 'Academic Periods',
                'ordering': ['-academic_year__year', '-semester__semester_type'],
            },
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['is_current', 'is_active'], name='attendance_a_is_curr_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['period_start', 'period_end'], name='attendance_a_period__123456_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['academic_year', 'semester'], name='attendance_a_academi_123456_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('academic_year', 'semester')},
        ),
    ]
