# Generated by Django 5.1.4 on 2025-09-19 19:33

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_add_academic_period_model'),
    ]

    operations = [
        # Add academic_period ForeignKey to TimetableSlot
        migrations.AddField(
            model_name='timetableslot',
            name='academic_period',
            field=models.ForeignKey(
                blank=True,
                help_text='Academic period for this timetable slot',
                null=True,
                on_delete=deletion.CASCADE,
                related_name='timetable_slots',
                to='attendance.academicperiod'
            ),
        ),
        
        # Add academic_period ForeignKey to AttendanceSession
        migrations.AddField(
            model_name='attendancesession',
            name='academic_period',
            field=models.ForeignKey(
                blank=True,
                help_text='Academic period for this session',
                null=True,
                on_delete=deletion.CASCADE,
                related_name='attendance_sessions',
                to='attendance.academicperiod'
            ),
        ),
        
        # Add academic_period ForeignKey to AttendanceRecord
        migrations.AddField(
            model_name='attendancerecord',
            name='academic_period',
            field=models.ForeignKey(
                blank=True,
                help_text='Academic period for this record',
                null=True,
                on_delete=deletion.CASCADE,
                related_name='attendance_records',
                to='attendance.academicperiod'
            ),
        ),
        
        # Add indexes for the new ForeignKey fields
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['academic_period', 'day_of_week', 'start_time'], name='attendance_t_academi_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['course_section', 'academic_period'], name='attendance_t_course__123456_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['faculty', 'academic_period'], name='attendance_t_faculty_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['is_active', 'academic_period'], name='attendance_t_is_acti_123456_idx'),
        ),
        
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['academic_period', 'scheduled_date'], name='attendance_a_academi_123456_idx'),
        ),
        
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['academic_period', 'marked_at'], name='attendance_r_academi_123456_idx'),
        ),
    ]
